### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by niallobr** [hojulian/tailscale-relay#1]
Hey there,

Thanks for your work putting this container together. Any chance you could update the Dockerfile to always grab the latest stable tailscale version? Or was there a particular need you had for version 1.2.10?

Thanks!

**Comment by hojulian** [comment]
Sorry I haven't updated this project in a while since it's not being used anymore. But you can build a new image with the tailscale version you want by changing the build-args.

For instance,
```
docker build --build-arg VERSION=1.8.5 -t tailscale-relay .
```

I haven't tested the newer tailscale versions, so I can't promise it will work.

**Comment by niallobr** [comment]
This worked perfectly. Thanks for the tip @hojulian :)
